apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCF62ihePldZcfgLLZa3UsAndnYj669kTucyD44aoczqlu0dLQ/DFehP3BzPSE4UBvOcnq+usE6XKIIa4mizI1S0aE0o+luXnn0dNJFMe6X0wuYzxUpciSXVgNmx7Gz7UX5f6l29xMBM7TwQAsTd+jUtfYeQVg0P6XbnJwSa25j3JL0QpNl8z9IfMNiKPn4IoI5OLohGBE/G8pRy9ljqTSBTr9szLLYMLIKk5vG/dGqHkdJfOWZfFQhuJv6S2Q2tey1UY6z3K//9UumBoXl8/eZ4TFqwGk6w7iL/BT/UifJzHQ2a4mjWvyMJzivPdLNVY1vU+O44olUIfyZJith26LPu0M9UHvOUFs34QqLi6q+jqtb2XzOlW27tG3FCcGLj1vmRMLWbFxGAOBVMYJIWjRSosB3RYACQwl0y6yrzCj+A2xxDBFpzmvXYEyzjaC82EEgEl9HZ44msVLKOC8j1ZYBfnl3ero0FH52bj8w//OGtMQquHjHoL4bT8PCDHAj7+jJ9zoUSzSfIQoJ0Tcw9v+2NzbIP8Upbi0ckWTxVWXGxQTuVO4nXrq36lYcK3ye0sCvhEuQGl84y31Mfyd8ESUnmQqtWDD8QtUYziSIgmfGChkfxLpQXAAOZTJCDml0S+ehwgJJ9aF/TN9Y0hYmFRjlmjkrEYmxe1Wvb5JgKefmV8tJIAqqB6f37QOY+DkP6E0pf1GpkV2tkCYpUA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

